export const CLUB_LIST_REQUEST = 'CLUB_LIST_REQUEST'
export const CLUB_LIST_SUCCESS = 'CLUB_LIST_SUCCESS'
export const CLUB_LIST_FAIL = 'CLUB_LIST_FAIL'

export const CLUB_DETAILS_REQUEST = 'CLUB_DETAILS_REQUEST'
export const CLUB_DETAILS_SUCCESS = 'CLUB_DETAILS_SUCCESS'
export const CLUB_DETAILS_FAIL = 'CLUB_DETAILS_FAIL'

export const CLUB_DELETE_REQUEST = 'CLUB_DELETE_REQUEST'
export const CLUB_DELETE_SUCCESS = 'CLUB_DELETE_SUCCESS'
export const CLUB_DELETE_FAIL = 'CLUB_DELETE_FAIL'

export const CLUB_CREATE_REQUEST = 'CLUB_CREATE_REQUEST'
export const CLUB_CREATE_SUCCESS = 'CLUB_CREATE_SUCCESS'
export const CLUB_CREATE_FAIL = 'CLUB_CREATE_FAIL'
export const CLUB_CREATE_RESET = 'CLUB_CREATE_RESET'


export const CLUB_UPDATE_REQUEST = 'CLUB_UPDATE_REQUEST'
export const CLUB_UPDATE_SUCCESS = 'CLUB_UPDATE_SUCCESS'
export const CLUB_UPDATE_FAIL = 'CLUB_UPDATE_FAIL'
export const CLUB_UPDATE_RESET = 'CLUB_UPDATE_RESET'

export const CLUB_CREATE_REVIEW_REQUEST = 'CLUB_CREATE_REVIEW_REQUEST'
export const CLUB_CREATE_REVIEW_SUCCESS = 'CLUB_CREATE_REVIEW_SUCCESS'
export const CLUB_CREATE_REVIEW_FAIL = 'CLUB_CREATE_REVIEW_FAIL'
export const CLUB_CREATE_REVIEW_RESET = 'CLUB_CREATE_REVIEW_RESET'

export const CLUB_CREATE_EVENT_REQUEST = 'CLUB_CREATE_EVENT_REQUEST'
export const CLUB_CREATE_EVENT_SUCCESS = 'CLUB_CREATE_EVENT_SUCCESS'
export const CLUB_CREATE_EVENT_FAIL = 'CLUB_CREATE_EVENT_FAIL'
export const CLUB_CREATE_EVENT_RESET = 'CLUB_CREATE_EVENT_RESET'

export const CLUB_TOP_REQUEST = 'CLUB_TOP_REQUEST'
export const CLUB_TOP_SUCCESS = 'CLUB_TOP_SUCCESS'
export const CLUB_TOP_FAIL = 'CLUB_TOP_FAIL'