# Generated by Django 4.1.4 on 2023-01-02 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_eventrequest_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.club'),
        ),
    ]
