# Generated by Django 4.1.4 on 2023-01-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_review_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='quota',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
