# Generated by Django 4.1.4 on 2023-01-02 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_club_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
